### ISSUE TITLE
Add php7 support

### ISSUE THREAD

**Issue by AlexGx** [bullsoft/php-binlog#6]
Add php7 support

**Comment by ideal** [comment]
@AlexGx Hi, we are thinking to rewrite this extension, to include mysql-replication-listener (so need not to compile twice), and php 7 support.

**Comment by lifeofguenter** [comment]
Any progress on that :) ?

**Comment by ideal** [comment]
Will start work with @guweigang . Another extension (https://github.com/bullsoft/php-pinyin is already php 7 compatible). Sorry for delay.

**Comment by guweigang** [comment]
The new branch `bundle-new-binlog` is now support `Mysql 5.7` and `PHP 7`.

**Comment by lifeofguenter** [comment]
awesome news @guweigang + @ideal ! Thanks :)

**Comment by guweigang** [comment]
@lifeofguenter  please use the  new `cpp_ext`  extension.
